cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'vlc'
